BEGIN;
CREATE TABLE IF NOT EXISTS business_calendars (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name varchar(100) NOT NULL, timezone varchar(100) NOT NULL DEFAULT 'UTC', calendar_type varchar(30) NOT NULL DEFAULT 'TWENTY_FOUR_SEVEN', weekly_schedule jsonb, holidays jsonb DEFAULT '[]'::jsonb, active boolean NOT NULL DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, UNIQUE(organization_id,name));
CREATE TABLE IF NOT EXISTS sla_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name varchar(120) NOT NULL, ticket_type_id uuid REFERENCES ticket_types(id), priority_id uuid REFERENCES priorities(id), calendar_id uuid NOT NULL REFERENCES business_calendars(id), response_target_minutes integer NOT NULL CHECK(response_target_minutes>0), resolution_target_minutes integer NOT NULL CHECK(resolution_target_minutes>0), pause_statuses jsonb DEFAULT '[]'::jsonb, version integer NOT NULL DEFAULT 1, active boolean NOT NULL DEFAULT true, effective_from timestamp without time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, UNIQUE(organization_id,name,version));
CREATE TABLE IF NOT EXISTS ticket_slas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE, sla_definition_id uuid NOT NULL REFERENCES sla_definitions(id), definition_name varchar(120) NOT NULL, definition_version integer NOT NULL, response_target_minutes integer NOT NULL, resolution_target_minutes integer NOT NULL, started_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, response_due_at timestamp without time zone NOT NULL, resolution_due_at timestamp without time zone NOT NULL, first_responded_at timestamp without time zone, resolved_at timestamp without time zone, paused_at timestamp without time zone, total_paused_seconds integer NOT NULL DEFAULT 0, status varchar(30) NOT NULL DEFAULT 'IN_PROGRESS', created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, UNIQUE(ticket_id,sla_definition_id));
CREATE TABLE IF NOT EXISTS sla_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_sla_id uuid NOT NULL REFERENCES ticket_slas(id) ON DELETE CASCADE, event_type varchar(30) NOT NULL, event_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, details jsonb);
CREATE INDEX IF NOT EXISTS idx_ticket_slas_status_due ON ticket_slas(status,resolution_due_at);
CREATE INDEX IF NOT EXISTS idx_sla_events_ticket_time ON sla_events(ticket_sla_id,event_at);
INSERT INTO business_calendars(organization_id,name,timezone,calendar_type) SELECT id,'24x7 Default','UTC','TWENTY_FOUR_SEVEN' FROM organizations ON CONFLICT DO NOTHING;
COMMIT;
