import { FormEvent, useEffect, useState } from 'react';
import { api } from './api';
import type { AdminGroup, AdminUser, ReferenceData, SlaDefinition } from './types';
import { rawTimeZones } from '@vvo/tzdb';

const emptyReference: ReferenceData = { roles: [], departments: [], priorities: [], ticketTypes: [], calendars: [] };
const timezones = rawTimeZones.map(zone => zone.name);

function CalendarEditor({ token, onCreated }: { token: string; onCreated: () => Promise<void> }) {
  const allDays = ['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'];
  const [name,setName]=useState('Business Hours'); const [timezone,setTimezone]=useState('Asia/Kolkata'); const [days,setDays]=useState(allDays.slice(0,5)); const [start,setStart]=useState('09:00'); const [end,setEnd]=useState('17:00'); const [holidays,setHolidays]=useState(''); const [busy,setBusy]=useState(false);
  async function save(){const weeklySchedule=Object.fromEntries(days.map(day=>[day,[{start,end}]]));setBusy(true);try{await api.createBusinessCalendar(token,{name,timezone,calendarType:'BUSINESS_HOURS',weeklySchedule,holidays:holidays.split(',').map(value=>value.trim()).filter(Boolean)});await onCreated();setName('Business Hours')}finally{setBusy(false)}}
  return <div className="calendar-editor"><h2>Business Calendar Editor</h2><p className="muted">Configure working days, hours, timezone, and holiday dates.</p><div className="calendar-fields"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Timezone<select value={timezone} onChange={e=>setTimezone(e.target.value)}>{timezones.map(value=><option key={value}>{value}</option>)}</select></label><label>Start<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="day-picker">{allDays.map(day=><label key={day}><input type="checkbox" checked={days.includes(day)} onChange={()=>setDays(current=>current.includes(day)?current.filter(value=>value!==day):[...current,day])}/>{day.slice(0,3)}</label>)}</div><label className="holiday-field">Holidays <small>Comma-separated dates, e.g. 2026-08-15, 2026-10-02</small><input value={holidays} onChange={e=>setHolidays(e.target.value)} placeholder="YYYY-MM-DD"/></label><button className="primary" onClick={save} disabled={busy||!name||days.length===0||start>=end}>Create business calendar</button></div>;
}

export default function AdminConsole({ token, onClose }: { token: string; onClose: () => void }) {
  const [tab,setTab]=useState<'users'|'groups'|'slas'>('users'); const [users,setUsers]=useState<AdminUser[]>([]); const [groups,setGroups]=useState<AdminGroup[]>([]); const [slas,setSlas]=useState<SlaDefinition[]>([]); const [reference,setReference]=useState(emptyReference); const [page,setPage]=useState(1); const [totalPages,setTotalPages]=useState(1); const [total,setTotal]=useState(0); const [search,setSearch]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [newUser,setNewUser]=useState({name:'',email:'',departmentId:'',temporaryPassword:''}); const [newGroup,setNewGroup]=useState({name:'',description:''}); const [newSla,setNewSla]=useState({name:'',ticketTypeId:'',priorityId:'',calendarId:'',responseTargetMinutes:60,resolutionTargetMinutes:480,pauseStatuses:['AWAITING_CUSTOMER']});
  const [calendarName,setCalendarName]=useState('Standard Business Hours'); const [calendarTimezone,setCalendarTimezone]=useState('Asia/Kolkata');
  async function load(){try{const [u,g,r,s]=await Promise.all([api.adminUsers(token,page,search),api.adminGroups(token),api.adminReferenceData(token),api.adminSlas(token)]);setUsers(u.data);setTotal(u.total);setTotalPages(u.totalPages);setGroups(g);setReference(r);setSlas(s);setNewSla(value=>({...value,calendarId:value.calendarId||r.calendars[0]?.id||'',ticketTypeId:value.ticketTypeId||r.ticketTypes.find(type=>type.name==='INCIDENT')?.id||''}))}catch(reason){setError(reason instanceof Error?reason.message:'Could not load admin data')}}
  useEffect(()=>{void load()},[token,page,search]);
  const effectiveRoles=(user:AdminUser)=>[...new Set(['EMPLOYEE',...user.directRoles.map(x=>x.role.name),...user.assignmentGroupMemberships.flatMap(m=>m.assignmentGroup.roles.map(x=>x.role.name))])];
  async function createUser(e:FormEvent){e.preventDefault();setBusy(true);try{await api.createAdminUser(token,{...newUser,departmentId:newUser.departmentId||undefined});setNewUser({name:'',email:'',departmentId:'',temporaryPassword:''});await load()}finally{setBusy(false)}}
  async function createGroup(e:FormEvent){e.preventDefault();setBusy(true);try{await api.createAdminGroup(token,newGroup);setNewGroup({name:'',description:''});await load()}finally{setBusy(false)}}
  async function createSla(e:FormEvent){e.preventDefault();setBusy(true);try{await api.createAdminSla(token,{...newSla,priorityId:newSla.priorityId||undefined,ticketTypeId:newSla.ticketTypeId||undefined});setNewSla(v=>({...v,name:''}));await load()}finally{setBusy(false)}}
  async function createCalendar(){const weekdays=['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY'];const weeklySchedule=Object.fromEntries(weekdays.map(day=>[day,[{start:'09:00',end:'17:00'}]]));setBusy(true);try{await api.createBusinessCalendar(token,{name:calendarName,timezone:calendarTimezone,calendarType:'BUSINESS_HOURS',weeklySchedule,holidays:[]});await load()}finally{setBusy(false)}}
  return <div className="admin-overlay"><section className="admin-console"><header><div><p className="eyebrow">PLATFORM ADMINISTRATION</p><h1>Admin Console</h1><p>Manage people, resolver teams, and service targets.</p></div><button className="icon-button" onClick={onClose}>×</button></header><div className="record-tabs"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>Users</button><button className={tab==='groups'?'active':''} onClick={()=>setTab('groups')}>Assignment Groups</button><button className={tab==='slas'?'active':''} onClick={()=>setTab('slas')}>SLA Policies</button></div>{error&&<div className="error">{error}</div>}
    {tab==='users'&&<div className="admin-grid"><form className="admin-form" onSubmit={createUser}><h2>Add user</h2><p className="muted">Employee access is automatic; elevated access comes from groups.</p><label>Name<input required value={newUser.name} onChange={e=>setNewUser({...newUser,name:e.target.value})}/></label><label>Email<input required type="email" value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/></label><label>Department<select value={newUser.departmentId} onChange={e=>setNewUser({...newUser,departmentId:e.target.value})}><option value="">No department</option>{reference.departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Temporary password<input required minLength={8} type="password" value={newUser.temporaryPassword} onChange={e=>setNewUser({...newUser,temporaryPassword:e.target.value})}/></label><button className="primary" disabled={busy}>Create user</button></form><div className="admin-list"><div className="admin-list-head"><h2>Users <span>{total}</span></h2><input placeholder="Search name or email" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div>{users.map(u=><article key={u.id}><div className="avatar">{u.name.slice(0,2).toUpperCase()}</div><div><b>{u.name}</b><small>{u.email}</small></div><span className="role-pill">{effectiveRoles(u).join(', ')}</span><button className="secondary small" onClick={async()=>{await api.updateAdminUser(token,u.id,{active:!u.active});await load()}}>{u.active?'Deactivate':'Activate'}</button></article>)}<div className="pagination"><button className="secondary small" disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Previous</button><span>Page {page} of {totalPages}</span><button className="secondary small" disabled={page>=totalPages} onClick={()=>setPage(v=>v+1)}>Next</button></div></div></div>}
    {tab==='groups'&&<div className="admin-grid"><form className="admin-form" onSubmit={createGroup}><h2>Add assignment group</h2><label>Name<input required value={newGroup.name} onChange={e=>setNewGroup({...newGroup,name:e.target.value})}/></label><label>Description<textarea rows={4} value={newGroup.description} onChange={e=>setNewGroup({...newGroup,description:e.target.value})}/></label><button className="primary">Create group</button></form><div className="admin-list"><h2>Assignment Groups <span>{groups.length}</span></h2>{groups.map(g=><article className="group-card" key={g.id}><b>{g.name}</b><small>{g.description||'No description'}</small><div className="member-list role-list">{g.roles.map(x=><span key={x.role.id}>{x.role.name}<button onClick={async()=>{await api.removeGroupRole(token,g.id,x.role.id);await load()}}>×</button></span>)}</div><select defaultValue="" onChange={async e=>{if(e.target.value)await api.addGroupRole(token,g.id,e.target.value);e.target.value='';await load()}}><option value="">Grant role…</option>{reference.roles.filter(r=>r.name!=='EMPLOYEE'&&!g.roles.some(x=>x.role.id===r.id)).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><div className="member-list">{g.members.map(x=><span key={x.user.id}>{x.user.name}<button onClick={async()=>{await api.removeGroupMember(token,g.id,x.user.id);await load()}}>×</button></span>)}</div><select defaultValue="" onChange={async e=>{if(e.target.value)await api.addGroupMember(token,g.id,e.target.value);e.target.value='';await load()}}><option value="">Add member…</option>{users.filter(u=>u.active&&!g.members.some(x=>x.user.id===u.id)).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></article>)}</div></div>}
    {tab==='slas'&&<div className="admin-grid"><div className="admin-form-stack"><form className="admin-form" onSubmit={createSla}><h2>Add SLA policy</h2><label>Name<input required value={newSla.name} onChange={e=>setNewSla({...newSla,name:e.target.value})}/></label><label>Ticket type<select value={newSla.ticketTypeId} onChange={e=>setNewSla({...newSla,ticketTypeId:e.target.value})}>{reference.ticketTypes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Priority<select value={newSla.priorityId} onChange={e=>setNewSla({...newSla,priorityId:e.target.value})}><option value="">All priorities</option>{reference.priorities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Calendar<select value={newSla.calendarId} onChange={e=>setNewSla({...newSla,calendarId:e.target.value})}>{reference.calendars.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Response target (minutes)<input type="number" min={1} value={newSla.responseTargetMinutes} onChange={e=>setNewSla({...newSla,responseTargetMinutes:Number(e.target.value)})}/></label><label>Resolution target (minutes)<input type="number" min={1} value={newSla.resolutionTargetMinutes} onChange={e=>setNewSla({...newSla,resolutionTargetMinutes:Number(e.target.value)})}/></label><button className="primary">Create SLA</button></form><div className="admin-form"><h2>Add business calendar</h2><p className="muted">Monday–Friday, 09:00–17:00. Holidays can be added in the next calendar editor iteration.</p><label>Name<input value={calendarName} onChange={e=>setCalendarName(e.target.value)}/></label><label>Timezone<select value={calendarTimezone} onChange={e=>setCalendarTimezone(e.target.value)}>{timezones.map(timezone=><option key={timezone} value={timezone}>{timezone}</option>)}</select></label><button className="primary" type="button" onClick={createCalendar} disabled={busy}>Create calendar</button></div></div><div className="admin-list"><h2>SLA Policies <span>{slas.length}</span></h2>{slas.map(s=><article className="sla-card" key={s.id}><div><b>{s.name} · v{s.version}</b><small>{s.ticketType?.name||'All tickets'} · {s.priority?.name||'All priorities'} · {s.calendar.name}</small></div><div><span>Response: {s.responseTargetMinutes} min</span><span>Resolution: {s.resolutionTargetMinutes} min</span></div><button className="secondary small" disabled={!s.active} onClick={async()=>{await api.deactivateAdminSla(token,s.id);await load()}}>{s.active?'Deactivate':'Inactive'}</button></article>)}</div></div>}
    {tab==='slas'&&<CalendarEditor token={token} onCreated={load}/>}</section></div>;
}
